In [7]:
import jax.numpy as jnp
import chex
import numpy as np
from os import PathLike
import pandas as pd

In [8]:
chex.assert_gpu_available()

In [15]:
def load_data(path: PathLike):
    df = pd.read_csv(path, sep="\t", names=["X", "Y", "Wave", "Intensity"], comment="#")
    repetitions = df["Wave"].value_counts()[df["Wave"].iloc[0]]
    raman_shift = np.asarray(np.split(df["Wave"].values, repetitions))
    row_perm = np.argsort(raman_shift, axis = 1)
    raman_shift = raman_shift[:, row_perm]
    counts = np.asarray(np.split(df["Intensity"].values, repetitions))
    sorted_counts = []
    for row_idx, row in enumerate(counts):
        sorted_counts.append(row[row_perm[row_idx]])
    counts = np.stack(sorted_counts)
    raman_shift = raman_shift
    return {"raman_shift": raman_shift, "counts": counts}

In [17]:
dataset = load_data('../data/Mixed_8x8.txt')

In [19]:
dataset['raman_shift'].shape, dataset['counts'].shape

((64, 64, 1015), (64, 1015))

In [25]:
raw_data = np.loadtxt('../data/Mixed_8x8.txt')

In [28]:
np.unique(raw_data[:, 2], return_counts=True)

(array([1278.599609, 1280.300781, 1282.      , ..., 2817.944336,
        2819.305664, 2820.666016]),
 array([64, 64, 64, ..., 64, 64, 64]))

In [29]:
# Make a dataset out of a txt file and save it in npz format
raw_data

array([[-1201.459601, -2642.0595  ,  2820.666016,    82.669746],
       [-1201.459601, -2642.0595  ,  2819.305664,    60.624485],
       [-1201.459601, -2642.0595  ,  2817.944336,   101.019485],
       ...,
       [-1201.459601, -2635.0595  ,  1282.      ,   123.563843],
       [-1201.459601, -2635.0595  ,  1280.300781,   105.88765 ],
       [-1201.459601, -2635.0595  ,  1278.599609,    99.982147]])